import { RadioStation } from "@/types/radio";

// Mock data for Tanzanian radio stations
export const mockStations: RadioStation[] = [
  {
    changeuuid: "mock1",
    stationuuid: "mock1",
    name: "TBC Taifa",
    url: "https://eatv.radioca.st/stream",
    url_resolved: "https://eatv.radioca.st/stream",
    homepage: "https://www.tbc.go.tz/",
    favicon: "https://cdn-radiotime-logos.tunein.com/s88252q.png",
    tags: "news,talk,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "Swahili",
    votes: 10,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 1000,
    clicktrend: 5,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  },
  {
    changeuuid: "mock2",
    stationuuid: "mock2",
    name: "Radio One",
    url: "https://radiodart.co.tz:8000/stream",
    url_resolved: "https://radiodart.co.tz:8000/stream",
    homepage: "https://www.ippmedia.com/",
    favicon: "https://cdn-profiles.tunein.com/s88254/images/logog.png",
    tags: "music,entertainment,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "Swahili",
    votes: 8,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 800,
    clicktrend: 3,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  },
  {
    changeuuid: "mock3",
    stationuuid: "mock3",
    name: "Clouds FM",
    url: "https://cloudsradio.co.tz/stream",
    url_resolved: "https://cloudsradio.co.tz/stream",
    homepage: "https://cloudsmedia.co.tz/",
    favicon: "https://cdn-radiotime-logos.tunein.com/s88255q.png",
    tags: "music,entertainment,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "Swahili",
    votes: 12,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 1200,
    clicktrend: 7,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  },
  {
    changeuuid: "mock4",
    stationuuid: "mock4",
    name: "East Africa Radio",
    url: "https://eatv.radioca.st/stream",
    url_resolved: "https://eatv.radioca.st/stream",
    homepage: "https://eafm.co.tz/",
    favicon: "https://cdn-profiles.tunein.com/s88256/images/logog.png",
    tags: "music,entertainment,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "Swahili",
    votes: 9,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 950,
    clicktrend: 4,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  },
  {
    changeuuid: "mock5",
    stationuuid: "mock5",
    name: "Times FM",
    url: "https://timesfm.co.tz/stream",
    url_resolved: "https://timesfm.co.tz/stream",
    homepage: "https://timesfm.co.tz/",
    favicon: "https://cdn-profiles.tunein.com/s88257/images/logog.png",
    tags: "news,talk,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "Swahili",
    votes: 7,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 750,
    clicktrend: 2,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  },
  {
    changeuuid: "mock6",
    stationuuid: "mock6",
    name: "Capital Radio",
    url: "https://capitalradio.co.tz/stream",
    url_resolved: "https://capitalradio.co.tz/stream",
    homepage: "https://capitalradio.co.tz/",
    favicon: "https://cdn-profiles.tunein.com/s88258/images/logog.png",
    tags: "news,business,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "English",
    votes: 6,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 600,
    clicktrend: 1,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  },
  {
    changeuuid: "mock7",
    stationuuid: "mock7",
    name: "Magic FM",
    url: "https://magicfm.co.tz/stream",
    url_resolved: "https://magicfm.co.tz/stream",
    homepage: "https://magicfm.co.tz/",
    favicon: "https://cdn-profiles.tunein.com/s88259/images/logog.png",
    tags: "music,entertainment,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "Swahili",
    votes: 5,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 500,
    clicktrend: 0,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  },
  {
    changeuuid: "mock8",
    stationuuid: "mock8",
    name: "Radio Free Africa",
    url: "https://radiofreeafrica.co.tz/stream",
    url_resolved: "https://radiofreeafrica.co.tz/stream",
    homepage: "https://radiofreeafrica.co.tz/",
    favicon: "https://cdn-profiles.tunein.com/s88260/images/logog.png",
    tags: "news,talk,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "Swahili",
    votes: 4,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 400,
    clicktrend: -1,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  },
  {
    changeuuid: "mock9",
    stationuuid: "mock9",
    name: "Radio Maria Tanzania",
    url: "https://radiomaria.co.tz/stream",
    url_resolved: "https://radiomaria.co.tz/stream",
    homepage: "https://radiomaria.co.tz/",
    favicon: "https://cdn-profiles.tunein.com/s88261/images/logog.png",
    tags: "religious,christian,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "Swahili",
    votes: 3,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 300,
    clicktrend: -2,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  },
  {
    changeuuid: "mock10",
    stationuuid: "mock10",
    name: "Bongo Radio",
    url: "https://bongoradio.com/stream",
    url_resolved: "https://bongoradio.com/stream",
    homepage: "https://bongoradio.com/",
    favicon: "https://cdn-profiles.tunein.com/s88262/images/logog.png",
    tags: "music,bongo flava,tanzania",
    country: "Tanzania",
    countrycode: "TZ",
    language: "Swahili",
    votes: 11,
    lastchangetime: "",
    codec: "MP3",
    bitrate: 128,
    clickcount: 1100,
    clicktrend: 6,
    ssl_error: 0,
    geo_lat: null,
    geo_long: null,
    has_extended_info: false
  }
];
